#include <QApplication>
#include <QPushButton>
#include <widgets/MainWindow.h>
#include <net/net.h>
#include <iostream>
#include <string>
#include <nlohmann/json.hpp>

#include <models/School.h>
#include <models/User.h>
#include <net/auth.h>
#include <net/schools.h>
#include <net/courses.h>

using namespace std;

int main(int argc, char *argv[]) {
    QApplication a(argc, argv);
    MainWindow window(nullptr);
    QPushButton button("Hello world!", &window);
    window.show();

    net::init();
    bool netStat = net::getStatus();
    if(netStat) {
        string email = "dummy@gregk.ca";
        string password = "password";
        net::auth::login(email, password);
        cout << "Logged in as " << net::auth::localUser->getName() << endl;
    } else {
        cout << "API connection failed" << endl;
    }

    auto schools = net::schools::getSchools();
    for(auto &school : *schools){
        cout << school.getName() << " " << school.getId() << endl;
        auto courses = *net::schools::getCourses(school);
        for(auto &course : courses){
            cout << course.getCode() << ":" << course.getName() << endl;
        }
    }

    nlohmann::json courseJSON = {
            {"id", ""}, // ID will be generated by database
            {"name", "Testing Course"},
            {"code", "TEST123"},
            {"year", 2021},
            {"term", enums::Term::FALL.toDB()},
            {"prof", "Brown"},
            {"owner", ""}, // Owner will be filled by backend
            {"school", "5cd83d02-2dcf-11ec-a3fd-0023aea14009"},
            {"modified", 0}
    };

    cout << "Creating course" << endl;
    Course tmp(courseJSON);

    auto c = net::courses::add(tmp);

    cout << c->getId() << endl;

    string newName = "New Test Name";
    c->setName(newName);

    cout << "Updating course" << endl;
    c = net::courses::modify(*c);

    cout << "Deleting course" << endl;
    net::courses::remove(*c);


    return QApplication::exec();
}
